[build]
builder = "nixpacks"

[deploy]
startCommand = "streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false"
healthcheckPath = "/"
healthcheckTimeout = 300

[variables]
# Environment variables
STREAMLIT_SERVER_PORT = "8080"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true" 